$(document).ready(function() {
    $("#cabecalho").html(
        '<div style="background: url(imagens/barra_colorida.png) repeat-x;margin-bottom:0;padding-bottom:0;">.</div>'
        +'<div class="tudo" style="margin-top:0;padding-top:0;margin-bottom:2%;">'
        +'<nav class="nav img-fluid" style="padding:0 13%">'
        +'<img src="imagens/logotipo.png" alt="Ilha Criativa - Logo" style="width:12rem;height:6rem;margin:.5% 2%" />'
        +'<a style="padding:3% 2% 4%;" class="nav-link active" href="#">Home</a>'
        +'<a style="padding:3% 2% 4%;" class="nav-link" href="#">Empresa</a>'
        +'<a style="padding:3% 2% 4%;" class="nav-link" href="#">Portifólio</a>'
        +'<a style="padding:3% 2% 4%;" class="nav-link" href="#">Preços</a>'
        +'<a style="padding:3% 2% 4%;" class="nav-link" href="#">#Depoimentos</a>'
        +'<a style="padding:3% 2% 4%;" class="nav-link" href="#">Contato</a>'
        +'<div class="nav-link">'
        +'<a style="margin:3%;" class="text-secondary" href="#">(17) 3043-1521</a>'
        +'<a style="margin:3% 0 0;padding:4%;font-size:.8em" class="badge badge-pill badge-success" href="#">(17) 99653-0534 <i class="fa fa-whatsapp" aria-hidden="true"></i></a>'
        +'</div>'
        +'</nav>'
        +'</div>'
    );
    $("#rodape").html(
        '<div style="position:relative">'
        +'<img src="imagens/selo.png" alt="Selo de Segurança" style="position:absolute;padding:0 0 0 13%;margin-top:-.5%;width:21%">'
        +'<div style="background: url(imagens/faixa_amarela.png);padding:0 13% 0 13%;margin-top:3%;background-repeat:no-repeat">'
        +'<p class="text-justify" style="padding:3% 0 3% 25%;margin:0">'
        +'Compre com segurança, <span>não ficando satisfeito</span>,'
        +'<br><span>devolvemos seu dinheiro</span> sem perguntas ou questionamentos!'
        +'</p>'
        +'</div>'
        +'<div style="background:#00a9d6;padding:2%" class="row">'
        +'<div class="col-md-3">'
        +'<img src="imagens/via_whastapp.png" alt="" style="padding-top:15%;width:45%">'
        +'</div>'
        +'<div class="col-md-2">'
        +'<p>#Precisa de ajuda?</p>'
        +'</div>'
        +'<div class="col-md-2">'
        +'<p>#Sobre a Ilha</p>'
        +'</div>'
        +'<div class="col-md-2" style="background:#0039d6"></div>'
        +'<div class="col-md-3">'
        +'<p>Redes Sociais</p>'
        +'<div class="row">'
        +'<img src="imagens/facebook.png" alt="" style="margin:1%;">'
        +'<img src="imagens/youtube.png" alt="" style="margin:1%;">'
        +'<img src="imagens/twitter.png" alt="" style="margin:1%;">'
        +'</div>'
        +'</div>'
        +'</div>'
        +'</div>'
        
        
    );
});